"""Interactive setup wizard for fangbot init."""

from __future__ import annotations

import asyncio
import shutil
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from fangbot.config import FANGBOT_HOME

console = Console()

PROVIDERS = {
    "1": ("claude", "ANTHROPIC_API_KEY", "Anthropic Claude"),
    "2": ("openai", "OPENAI_API_KEY", "OpenAI"),
}


def _check_mcp_server() -> str | None:
    """Check if open-medicine-mcp is available. Returns the resolved command or None."""
    # Direct binary (production install via pipx/uv tool)
    if shutil.which("open-medicine-mcp"):
        return "open-medicine-mcp"
    # Fallback: available through uv run (dev mode)
    if shutil.which("uv"):
        return "uv"
    return None


def _prompt_provider() -> tuple[str, str, str]:
    """Prompt user to select a provider. Returns (provider_name, env_var_name, display_name)."""
    table = Table(title="LLM Providers", border_style="dim", show_header=True)
    table.add_column("#", style="bold", width=4, justify="right")
    table.add_column("Provider")
    table.add_column("Description")
    table.add_row("1", "Claude", "Anthropic Claude (recommended for clinical reasoning)")
    table.add_row("2", "OpenAI", "GPT-4o, GPT-5, o-series reasoning models")
    console.print(table)
    console.print()

    while True:
        try:
            choice = console.input("[bold cyan]Select provider (1-2):[/bold cyan] ").strip()
        except (EOFError, KeyboardInterrupt):
            raise SystemExit(0)
        if choice in PROVIDERS:
            return PROVIDERS[choice]
        console.print("[red]Please enter 1 or 2.[/red]")


def _prompt_api_key(env_var: str, display_name: str) -> str:
    """Prompt for API key with masked input."""
    console.print(f"\n[dim]Your {display_name} API key will be stored in ~/.fangbot/.env[/dim]")
    while True:
        try:
            key = console.input(f"[bold cyan]{env_var}:[/bold cyan] ").strip()
        except (EOFError, KeyboardInterrupt):
            raise SystemExit(0)
        if key:
            return key
        console.print("[red]API key cannot be empty.[/red]")


def _write_env_file(provider: str, env_var: str, api_key: str, mcp_command: str) -> Path:
    """Write the ~/.fangbot/.env file."""
    FANGBOT_HOME.mkdir(parents=True, exist_ok=True)

    env_path = FANGBOT_HOME / ".env"

    # Preserve existing keys if file exists
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()

    # Update with new values
    existing[env_var] = api_key
    existing["FANGBOT_PROVIDER"] = provider

    # Set MCP command if using uv fallback
    if mcp_command == "uv":
        existing["FANGBOT_MCP_COMMAND"] = "uv"
        existing["FANGBOT_MCP_ARGS"] = "run,open-medicine-mcp"

    lines = [
        "# Fangbot configuration",
        "# Generated by: fangbot init",
        "",
    ]
    for k, v in existing.items():
        lines.append(f"{k}={v}")

    env_path.write_text("\n".join(lines) + "\n")
    env_path.chmod(0o600)  # restrict permissions — contains secrets
    return env_path


def _test_mcp_connection(mcp_command: str) -> bool:
    """Test that the MCP server can start and respond."""
    from fangbot.skills.mcp_client import OpenMedicineMCPClient

    args = ["run", "open-medicine-mcp"] if mcp_command == "uv" else []

    async def _test() -> bool:
        client = OpenMedicineMCPClient(command=mcp_command, args=args)
        async with client.connect():
            tools = await client.list_tools()
            return len(tools) > 0

    try:
        return asyncio.run(_test())
    except Exception:
        return False


def run_setup() -> None:
    """Run the interactive setup wizard."""
    console.print(Panel(
        "[bold]Welcome to Fangbot[/bold]\n\n"
        "This wizard will configure your LLM provider and verify\n"
        "the OpenMedicine MCP server connection.\n\n"
        "[dim]Config will be saved to ~/.fangbot/.env[/dim]",
        title="fangbot init",
        border_style="blue",
    ))
    console.print()

    # Step 1: Check MCP server
    console.print("[bold]Step 1/3:[/bold] Checking OpenMedicine MCP server...")
    mcp_command = _check_mcp_server()
    if mcp_command is None:
        console.print(
            "[red]open-medicine-mcp not found.[/red]\n"
            "[dim]This shouldn't happen if fangbot was installed correctly.\n"
            "Try: pip install --force-reinstall fangbot[/dim]"
        )
        raise SystemExit(1)

    if mcp_command == "open-medicine-mcp":
        console.print("[green]  Found open-medicine-mcp on PATH[/green]")
    else:
        console.print("[yellow]  open-medicine-mcp not on PATH, using uv run fallback[/yellow]")
    console.print()

    # Step 2: Select provider and API key
    console.print("[bold]Step 2/3:[/bold] Configure LLM provider\n")
    provider, env_var, display_name = _prompt_provider()
    api_key = _prompt_api_key(env_var, display_name)
    console.print()

    # Step 3: Write config and test connection
    console.print("[bold]Step 3/3:[/bold] Saving configuration and testing connection...")
    env_path = _write_env_file(provider, env_var, api_key, mcp_command)
    console.print(f"[green]  Config saved to {env_path}[/green]")

    # Create logs directory
    logs_dir = FANGBOT_HOME / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    console.print(f"[green]  Logs directory: {logs_dir}[/green]")

    # Test MCP connection
    console.print("[dim]  Testing MCP connection...[/dim]")
    with console.status("[bold cyan]Connecting to OpenMedicine MCP server...[/bold cyan]"):
        mcp_ok = _test_mcp_connection(mcp_command)

    if mcp_ok:
        console.print("[green]  MCP connection successful![/green]")
    else:
        console.print(
            "[yellow]  MCP connection test failed.[/yellow]\n"
            "[dim]  fangbot chat will still work — the server may need a moment to start.[/dim]"
        )

    # Done
    console.print()
    console.print(Panel(
        f"[bold green]Setup complete![/bold green]\n\n"
        f"Provider: {display_name}\n"
        f"Config:   ~/.fangbot/.env\n"
        f"Logs:     ~/.fangbot/logs/\n\n"
        f"[bold]Next:[/bold] run [bold cyan]fangbot chat[/bold cyan] to start a session.",
        title="Ready",
        border_style="green",
    ))
